version: '3.8'

services:
  app1:
    build: ./app1
    container_name: flask_app1
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - db1
    environment:
      # - DATABASE_URL=postgresql://user1:password1@db1:5432/db1
      - DB_USER=user1
      - DB_PASSWORD=password1
      - DB_HOST=db1
      - DB_NAME=db1
      - DB_PORT=5432
    networks:
      - flask_network

  app2:
    build: ./app2
    container_name: flask_app2
    restart: always
    ports:
      - "5002:5000"
    depends_on:
      - db2
    environment:
      - DB_USER=user2
      - DB_PASSWORD=password2
      - DB_HOST=db2
      - DB_NAME=db2
      - DB_PORT=5432
    networks:
      - flask_network

  db1:
    image: postgres:latest
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    networks:
      - flask_network
    volumes:
      - db1_data:/var/lib/postgresql/data

  db2:
    image: postgres:latest
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    networks:
      - flask_network
    volumes:
      - db2_data:/var/lib/postgresql/data

networks:
  flask_network:
    driver: bridge

volumes:
  db1_data:
  db2_data:
